# Generated by Django 5.0.7 on 2024-08-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_father', models.CharField(max_length=100)),
                ('joindate', models.DateField()),
                ('stu_class', models.CharField(max_length=13, unique=True)),
                ('fees', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
        ),
    ]
