# Generated by Django 5.0.7 on 2024-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='stu_class',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
