# Generated by Django 5.1.1 on 2024-09-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='stu_class',
            field=models.CharField(max_length=20),
        ),
    ]
