# Generated by Django 5.0.7 on 2024-08-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Prfile',
                'verbose_name_plural': 'Prfiles',
            },
        ),
    ]
