# Generated by Django 5.0.7 on 2024-08-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('fees', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'TransportDetail',
                'verbose_name_plural': 'TransportDetails',
            },
        ),
    ]
