# Generated by Django 5.1.1 on 2024-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'RouteDetail',
                'verbose_name_plural': 'RouteDetails',
            },
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('fees', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'TransportDetail',
                'verbose_name_plural': 'TransportDetails',
            },
        ),
    ]
