# Generated by Django 5.0.7 on 2024-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'RouteDetail',
                'verbose_name_plural': 'RouteDetails',
            },
        ),
    ]
